"""remove filepath from documents

Revision ID: 1ec883625ed1
Revises: 67fc885526e4
Create Date: 2026-07-20 12:37:15.969126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec883625ed1'
down_revision: Union[str, Sequence[str], None] = '67fc885526e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'filepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
