"""add updated_at to conversation and document

Revision ID: ce1fcfda8bfd
Revises: 1ec883625ed1
Create Date: 2026-07-22 21:47:42.059704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1fcfda8bfd'
down_revision: Union[str, Sequence[str], None] = '1ec883625ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.drop_column('conversations', 'updated_at')
    # ### end Alembic commands ###
